In [2]:
# lấy các phần tử trong mảng theo yêu cầu

import numpy as np

row = 6
col = 8
 

m = np.random.randint(0, 100, [row, col])

v_m = []
v_s = []

print(m, '\n')
print('Kiểu dữ liệu: ', m.dtype)
print('Kích thước: ', m.shape)
print('Số phần tử: ', m.size)
print('Số chiều: ', m.ndim)

for i in range(0, min(row, col)):
    v_m.append(m[i, i])
    v_s.append(m[min(row, col) - i - 1, i])

v_m = np.array(v_m)
v_s = np.array(v_s)


print('Các phần tử nằm trền đường chéo chính: \n', v_m)
print('Các phần tử nằm trền đường chéo phụ: \n', v_s)

x = int(input('\nNhập vào giá trị x (0-100): '))

s_x = 0
e_x = 0
l_x = 0

for r in range(0, row):
    for c in range(0, col):
        if m[r, c] < x: 
            s_x += 1;
        elif m[r, c] == x:
            e_x += 1;
        else:
            l_x += 1;
            
print('----------------------')
print('Số phần tử < x: ', s_x)
print('Số phần tử = x: ', e_x)
print('Số phần tử > x: ', l_x)

[[68 90 89  0 62 55 80 58]
 [21 35 24 98 82 19 84 23]
 [81 17 83 28 87 19 79 55]
 [17 90 31 61 49 85 31 34]
 [16 13 52 23 20 72 66 76]
 [85 99 82 67 47 65 13 72]] 

Kiểu dữ liệu:  int32
Kích thước:  (6, 8)
Số phần tử:  48
Số chiều:  2
Các phần tử nằm trền đường chéo chính: 
 [68 35 83 61 20 65]
Các phần tử nằm trền đường chéo phụ: 
 [85 13 31 28 82 55]

Nhập vào giá trị x (0-100): 72
----------------------
Số phần tử < x:  30
Số phần tử = x:  2
Số phần tử > x:  16


In [2]:
# phân tích dữ liệu điểm
import numpy as np

scores = np.loadtxt('./data/scores.txt', delimiter = ',', dtype = np.int8)
print(scores, '\n')

scores_mean_std = np.array([])
student_std_max = [0, scores[:, 0].std()]
student_std_min = [0, scores[:, 0].std()]
for i in range(0, scores.shape[1]):
    scores_mean_std = np.append(scores_mean_std, scores[:, i].mean())
    
    i_std = scores[:, i].std()
    if(i_std > student_std_max[1]):
        student_std_max[0] = i
        student_std_max[1] = i_std
    
    if(i_std < student_std_min[1]):
        student_std_min[0] = i
        student_std_min[1] = i_std

scores_mean_sub = np.array([])
subject_std_max = [0, scores[0, :].std()]
subject_std_min = [0, scores[0, :].std()]
for i in range(0, scores.shape[0]):
    scores_mean_sub = np.append(scores_mean_sub, scores[i, :].mean())
    
    i_std = scores[i, :].std()
    if(i_std > subject_std_max[1]):
        subject_std_max[0] = i
        subject_std_max[1] = i_std
    
    if(i_std < subject_std_min[1]):
        subject_std_min[0] = i
        subject_std_min[1] = i_std
    
print('Điểm trung bình của từng học sinh trong lớp: \n', scores_mean_std)
print('------------------------------------------------------------')
print('Điểm trung bình cao nhất: ', scores_mean_std.max())
print('Của học sinh thứ: ', scores_mean_std.argmax() + 1)
print('Bảng điểm đầy đủ của học sinh: \n', scores[:, scores_mean_std.argmax()])
print('------------------------------------------------------------')
print('Điểm trung bình thấp nhất: ', scores_mean_std.min())
print('Của học sinh thứ: ', scores_mean_std.argmin() + 1)
print('Bảng điểm đầy đủ của học sinh: \n', scores[:, scores_mean_std.argmin()])

print('\n============================================================\n')

print('Điểm trung bình của từng môn học: \n', scores_mean_sub)
print('------------------------------------------------------------')
print('Điểm trung bình cao nhất: ', scores_mean_sub.max())
print('Của môn học thứ: ', scores_mean_sub.argmax() + 1)
print('Bảng điểm đầy đủ của môn học: \n', scores[scores_mean_sub.argmax(), :])
print('------------------------------------------------------------')
print('Điểm trung bình thấp nhất: ', scores_mean_sub.min())
print('Của môn học thứ: ', scores_mean_sub.argmin() + 1)
print('Bảng điểm đầy đủ của môn học: \n', scores[scores_mean_sub.argmin(), :]) 

print('\n============================================================\n')
print('Học sinh học đồng đều nhất: ', student_std_min[0])
print('Độ lệch: ', student_std_min[1])
print('Bảng điểm của học sinh học đồng đều: ', scores[:, student_std_min[0]])
print('------------------------------------------------------------')
print('Học sinh học lệch nhất: ', student_std_max[0])
print('Độ lệch: ', student_std_max[1])
print('Bảng điểm của học sinh học lệch: ', scores[:, student_std_max[0]])

print('\n')

print('Môn học có điểm đồng đều nhất: ', subject_std_min[0])
print('Độ lệch: ', subject_std_min[1])
print('Bảng điểm của môn học đồng đều: ', scores[subject_std_min[0], :])
print('------------------------------------------------------------')
print('Học sinh học lệch nhất: ', subject_std_max[0])
print('Độ lệch: ', subject_std_max[1])
print('Bảng điểm của Môn học lệch: ', scores[subject_std_max[0], :])

[[ 7  2  4 10  6  4  1 10  2 10  4  5  9  5  1  3  6  4  5  4]
 [ 4 10  8  8 10  7  6  3 10  6  8  4  5 10  9  8  2  5 10  9]
 [ 2  2  1  6  1  2  2  7  6  5  6  9  9  5 10  9  1  3  1  7]
 [ 1  6  4  5  2  2  2  8  7  2 10  7  7  9  8  7  6  2  5  7]
 [ 3  2  6  3  5  4  3  1  8  5  5  8  9  1  9  3  3  3  5  9]
 [ 9  2  6  7  9  7  7 10 10  9  7  3  9  2  7  4  8  4  5  1]
 [ 9  4  8  9  9  1  1  3  8  3  5  2  4  5  7  6  9  5  5  3]
 [ 7  3  4  9 10  4  4  8  1 10  6  3  4  7  6  6  1  4 10  7]
 [10  8 10  1  3  1  6 10  1  8  3 10  7 10  6  6  2  6  2  1]
 [10  1  4  8  9  7  8  9 10 10 10  8  7  9  3  2  9  1  6  4]] 

Điểm trung bình của từng học sinh trong lớp: 
 [6.2 4.  5.5 6.6 6.4 3.9 4.  6.9 6.3 6.8 6.4 5.9 7.  6.3 6.6 5.4 4.7 3.7
 5.4 5.2]
------------------------------------------------------------
Điểm trung bình cao nhất:  7.0
Của học sinh thứ:  13
Bảng điểm đầy đủ của học sinh: 
 [9 5 9 7 9 9 4 4 7 7]
------------------------------------------------------------
Điểm tr

In [37]:
# biến đổi dữ liệu
import numpy as np


v = np.arange(1, 31)

v_odd, v_even = np.hsplit(v.reshape(-1, 2), 2)
v_3 = np.hsplit(v.reshape(-1, 3), 3)[2]

print('Vector số lẻ: ', v_odd.ravel())
print('Vector số chẵn: ', v_even.ravel())
print('Vector chia hết cho 3: ', v_3.ravel())


Vector số lẻ:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
Vector số chẵn:  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
Vector chia hết cho 3:  [ 3  6  9 12 15 18 21 24 27 30]
